username = input("Введите уже имя пользователя")
title = input("Введите заголовок заметки")
content = input("Введите саму заметку")
status = input("Укажите статус заметки")
created_date = input("Введите дату создания")
issue_date = input("Введите дату (срок) выполнения")